# Generated by Django 4.0.1 on 2022-01-24 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='view_count',
        ),
    ]
